// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// DownloadsIdResponse defines model for DownloadsIdResponse.
type DownloadsIdResponse struct {
	Files []DownloadsIdResponse_Files_Item `json:"files"`

	// Id ID заявки, по которому можно опрашивать статус скачивания файлов
	Id int `json:"id"`

	// Status текущий статус заявки
	Status string `json:"status"`
}

// DownloadsIdResponse_Files_Item defines model for DownloadsIdResponse.files.Item.
type DownloadsIdResponse_Files_Item struct {
	union json.RawMessage
}

// DownloadsRequest defines model for DownloadsRequest.
type DownloadsRequest struct {
	// Files массив URL для скачивания
	Files []Url `json:"files"`

	// Timeout таймаут в секундах
	Timeout string `json:"timeout"`
}

// DownloadsResponse defines model for DownloadsResponse.
type DownloadsResponse struct {
	// Id ID заявки, по которому можно опрашивать статус скачивания файлов
	Id int `json:"id"`

	// Status начальный статус заявки
	Status string `json:"status"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Url defines model for Url.
type Url struct {
	// Url URL для скачивания файла
	Url UrlString `json:"url"`
}

// UrlErr defines model for UrlErr.
type UrlErr struct {
	Error struct {
		Code string `json:"code"`
	} `json:"error"`

	// Url URL для скачивания файла
	Url UrlString `json:"url"`
}

// UrlFile defines model for UrlFile.
type UrlFile struct {
	FileId int `json:"file_id"`

	// Url URL для скачивания файла
	Url UrlString `json:"url"`
}

// UrlString URL для скачивания файла
type UrlString = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// PostDownloadsJSONRequestBody defines body for PostDownloads for application/json ContentType.
type PostDownloadsJSONRequestBody = DownloadsRequest

// AsUrlFile returns the union data inside the DownloadsIdResponse_Files_Item as a UrlFile
func (t DownloadsIdResponse_Files_Item) AsUrlFile() (UrlFile, error) {
	var body UrlFile
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUrlFile overwrites any union data inside the DownloadsIdResponse_Files_Item as the provided UrlFile
func (t *DownloadsIdResponse_Files_Item) FromUrlFile(v UrlFile) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUrlFile performs a merge with any union data inside the DownloadsIdResponse_Files_Item, using the provided UrlFile
func (t *DownloadsIdResponse_Files_Item) MergeUrlFile(v UrlFile) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsUrlErr returns the union data inside the DownloadsIdResponse_Files_Item as a UrlErr
func (t DownloadsIdResponse_Files_Item) AsUrlErr() (UrlErr, error) {
	var body UrlErr
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUrlErr overwrites any union data inside the DownloadsIdResponse_Files_Item as the provided UrlErr
func (t *DownloadsIdResponse_Files_Item) FromUrlErr(v UrlErr) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUrlErr performs a merge with any union data inside the DownloadsIdResponse_Files_Item, using the provided UrlErr
func (t *DownloadsIdResponse_Files_Item) MergeUrlErr(v UrlErr) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t DownloadsIdResponse_Files_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DownloadsIdResponse_Files_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Download files
	// (POST /downloads)
	PostDownloads(w http.ResponseWriter, r *http.Request)
	// Просмотр статусов
	// (GET /downloads/{id})
	GetDownloadsId(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Download files
// (POST /downloads)
func (_ Unimplemented) PostDownloads(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Просмотр статусов
// (GET /downloads/{id})
func (_ Unimplemented) GetDownloadsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDownloads operation middleware
func (siw *ServerInterfaceWrapper) PostDownloads(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDownloads(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDownloadsId operation middleware
func (siw *ServerInterfaceWrapper) GetDownloadsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownloadsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads", wrapper.PostDownloads)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads/{id}", wrapper.GetDownloadsId)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type PostDownloadsRequestObject struct {
	Body *PostDownloadsJSONRequestBody
}

type PostDownloadsResponseObject interface {
	VisitPostDownloadsResponse(w http.ResponseWriter) error
}

type PostDownloads201JSONResponse DownloadsResponse

func (response PostDownloads201JSONResponse) VisitPostDownloadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostDownloads400JSONResponse struct{ BadRequestJSONResponse }

func (response PostDownloads400JSONResponse) VisitPostDownloadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsIdRequestObject struct {
	Id int `json:"id"`
}

type GetDownloadsIdResponseObject interface {
	VisitGetDownloadsIdResponse(w http.ResponseWriter) error
}

type GetDownloadsId201JSONResponse DownloadsIdResponse

func (response GetDownloadsId201JSONResponse) VisitGetDownloadsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsId400JSONResponse struct{ BadRequestJSONResponse }

func (response GetDownloadsId400JSONResponse) VisitGetDownloadsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Download files
	// (POST /downloads)
	PostDownloads(ctx context.Context, request PostDownloadsRequestObject) (PostDownloadsResponseObject, error)
	// Просмотр статусов
	// (GET /downloads/{id})
	GetDownloadsId(ctx context.Context, request GetDownloadsIdRequestObject) (GetDownloadsIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHttpHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHttpMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostDownloads operation middleware
func (sh *strictHandler) PostDownloads(w http.ResponseWriter, r *http.Request) {
	var request PostDownloadsRequestObject

	var body PostDownloadsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDownloads(ctx, request.(PostDownloadsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDownloads")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDownloadsResponseObject); ok {
		if err := validResponse.VisitPostDownloadsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDownloadsId operation middleware
func (sh *strictHandler) GetDownloadsId(w http.ResponseWriter, r *http.Request, id int) {
	var request GetDownloadsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDownloadsId(ctx, request.(GetDownloadsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDownloadsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDownloadsIdResponseObject); ok {
		if err := validResponse.VisitGetDownloadsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RW324bxRd+ldH59e63xC5wUfaOKgVFAlEl6lUU0LB7kmzl3dnOjIOsyFLsFAFqpT4B",
	"QogXWKIYXCd2XuHMG6Ezu/G/3eBKpEjcjWfG5zvnO99+c04hUmmuMsysgfAUNJpcZQb9j8cy3sUXXTSW",
	"f0Uqs5j5pczzThJJm6is9dyojPdMdIyp5NUDjYcQwv9ai9Ct8tS0nmit9G4FAv1+P4AYTaSTnINBCPQz",
	"jWhCM3fmznjlhjSlGY2EG9KIrmgm6E8q6Mad0cwNqAAOUUVn8G31XdZRMjY78RwmPIVcqxy1TcrCDpNO",
	"uUgspn6hMvzqEML9v8/+me58lnQQ+sHGe0+0hv5BALaXI4Sgvn2OkYX+fENqLXv8O4kZf5WEnW1fpXtD",
	"FzShcSDohgtnWoZMDc3o2p0LuqYZ/cH8CJp5Sgr3I43pggo3dK+FG7ihX567gXADmlDhfijPaUpj90a4",
	"l1TQW6aVLmCeW5JZPELN2RkrbdfUM/TdmLhz9xON6e0q0nLqi6DG6iQ78u3S+KKbaIwh3Ofy5yhB1Zgm",
	"2uZ9XVLkHU1dE9Q1FW7gBly3eLb7haBLuuLSG/iAYKGIDf1taqVNUlRd28gW08yZnLuhoAtG9/zRlC6p",
	"cN9DALm0FjVf/3q//cEnB/83DzayV9a8QN7A3F3fw39TgzT1sQq6cq9p6l7dmw6bWFw1rhqDkYr97hpI",
	"ACkaI4+aztYS8BEW95tyYNnVkLvl5ga57jWD8p/vQGIDq4Ehs/DO1TdV2IT2j0sIqsQOytS9Rzf6wzel",
	"0usau4cUbuNXSVR3a6rdYEGLz6HgmEqn0kIIXZ00SJifj+xQ1UH2kjTvoPj06Y6wSkQapcVAHKEVMosF",
	"syItCpWJVGVope4JmaouzwDsJZbpgy9Vhj2xh/okiXwoCOAEtSkRHm61t9rMnMoxk3kCIXzkt7yRHXvG",
	"W/Gt9fhuKNNgjfTrOgc0Yn5m3h2vaURT9hu6qPznhkZ+MLj0l6e3LjSlgn73U8M5m8DAvfKGMtkCn6H2",
	"s8pODCE8VcbOLRHKRqKxj1Xcu7cpp/ZY9VclY3UX/cbSsPVh++H7wL970tpWUTfFzFbyiLmZH7fbd8We",
	"J9taGgv98NVNU6l7PmIJK8pniQ8XEmidJnGfgx9hkwx+qQa6a35f3NmKefv2NnwtrJR54/nG0ktSb/zn",
	"aJeGQ69TLVO0qI0f/NYS+s0jTFaeFxrTZaXIsXtZHpev4TvmywMGR+dPBALIZOp9KIZ1dQRLnV53Kx4r",
	"3790lubnf0U8NQUsv+V+NvBpGNQntx3zpg3H1uZhq9VRkewcK2PDR+1Hbegf9P8KAAD//yd63KbcDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
