// Code generated by MockGen. DO NOT EDIT.
// Source: create_task.go

// Package task is a generated GoMock package.
package task

import (
	entity "bcc-go-project/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCreateTaskRepository is a mock of CreateTaskRepository interface.
type MockCreateTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskRepositoryMockRecorder
}

// MockCreateTaskRepositoryMockRecorder is the mock recorder for MockCreateTaskRepository.
type MockCreateTaskRepositoryMockRecorder struct {
	mock *MockCreateTaskRepository
}

// NewMockCreateTaskRepository creates a new mock instance.
func NewMockCreateTaskRepository(ctrl *gomock.Controller) *MockCreateTaskRepository {
	mock := &MockCreateTaskRepository{ctrl: ctrl}
	mock.recorder = &MockCreateTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTaskRepository) EXPECT() *MockCreateTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreateTaskRepository) Create(ctx context.Context, task entity.Task) (entity.IdTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(entity.IdTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreateTaskRepositoryMockRecorder) Create(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreateTaskRepository)(nil).Create), ctx, task)
}

// UpdateFileData mocks base method.
func (m *MockCreateTaskRepository) UpdateFileData(ctx context.Context, id entity.IdTask, url entity.Url, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileData", ctx, id, url, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFileData indicates an expected call of UpdateFileData.
func (mr *MockCreateTaskRepositoryMockRecorder) UpdateFileData(ctx, id, url, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileData", reflect.TypeOf((*MockCreateTaskRepository)(nil).UpdateFileData), ctx, id, url, data)
}

// UpdateFileErr mocks base method.
func (m *MockCreateTaskRepository) UpdateFileErr(ctx context.Context, id entity.IdTask, url entity.Url, fileErr error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileErr", ctx, id, url, fileErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFileErr indicates an expected call of UpdateFileErr.
func (mr *MockCreateTaskRepositoryMockRecorder) UpdateFileErr(ctx, id, url, fileErr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileErr", reflect.TypeOf((*MockCreateTaskRepository)(nil).UpdateFileErr), ctx, id, url, fileErr)
}

// UpdateStatus mocks base method.
func (m *MockCreateTaskRepository) UpdateStatus(ctx context.Context, id entity.IdTask, status entity.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCreateTaskRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCreateTaskRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockHttpLoader is a mock of HttpLoader interface.
type MockHttpLoader struct {
	ctrl     *gomock.Controller
	recorder *MockHttpLoaderMockRecorder
}

// MockHttpLoaderMockRecorder is the mock recorder for MockHttpLoader.
type MockHttpLoaderMockRecorder struct {
	mock *MockHttpLoader
}

// NewMockHttpLoader creates a new mock instance.
func NewMockHttpLoader(ctrl *gomock.Controller) *MockHttpLoader {
	mock := &MockHttpLoader{ctrl: ctrl}
	mock.recorder = &MockHttpLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpLoader) EXPECT() *MockHttpLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockHttpLoader) Load(ctx context.Context, url entity.Url) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, url)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockHttpLoaderMockRecorder) Load(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockHttpLoader)(nil).Load), ctx, url)
}
