// Code generated by MockGen. DO NOT EDIT.
// Source: get_task_file.go

// Package task is a generated GoMock package.
package task

import (
	entity "bcc-go-project/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskFileRepository is a mock of TaskFileRepository interface.
type MockTaskFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskFileRepositoryMockRecorder
}

// MockTaskFileRepositoryMockRecorder is the mock recorder for MockTaskFileRepository.
type MockTaskFileRepositoryMockRecorder struct {
	mock *MockTaskFileRepository
}

// NewMockTaskFileRepository creates a new mock instance.
func NewMockTaskFileRepository(ctrl *gomock.Controller) *MockTaskFileRepository {
	mock := &MockTaskFileRepository{ctrl: ctrl}
	mock.recorder = &MockTaskFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskFileRepository) EXPECT() *MockTaskFileRepositoryMockRecorder {
	return m.recorder
}

// GetTaskFile mocks base method.
func (m *MockTaskFileRepository) GetTaskFile(ctx context.Context, idTask entity.IdTask, idFile entity.IdFile) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskFile", ctx, idTask, idFile)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskFile indicates an expected call of GetTaskFile.
func (mr *MockTaskFileRepositoryMockRecorder) GetTaskFile(ctx, idTask, idFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskFile", reflect.TypeOf((*MockTaskFileRepository)(nil).GetTaskFile), ctx, idTask, idFile)
}
