// Code generated by MockGen. DO NOT EDIT.
// Source: get_task.go

// Package task is a generated GoMock package.
package task

import (
	entity "bcc-go-project/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGetTaskRepository is a mock of GetTaskRepository interface.
type MockGetTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGetTaskRepositoryMockRecorder
}

// MockGetTaskRepositoryMockRecorder is the mock recorder for MockGetTaskRepository.
type MockGetTaskRepositoryMockRecorder struct {
	mock *MockGetTaskRepository
}

// NewMockGetTaskRepository creates a new mock instance.
func NewMockGetTaskRepository(ctrl *gomock.Controller) *MockGetTaskRepository {
	mock := &MockGetTaskRepository{ctrl: ctrl}
	mock.recorder = &MockGetTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTaskRepository) EXPECT() *MockGetTaskRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGetTaskRepository) Get(ctx context.Context, id entity.IdTask) (*entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGetTaskRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetTaskRepository)(nil).Get), ctx, id)
}
