// Code generated by MockGen. DO NOT EDIT.
// Source: task_server.go

// Package server is a generated GoMock package.
package server

import (
	entity "bcc-go-project/internal/domain/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskCreateUseCase is a mock of TaskCreateUseCase interface.
type MockTaskCreateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskCreateUseCaseMockRecorder
}

// MockTaskCreateUseCaseMockRecorder is the mock recorder for MockTaskCreateUseCase.
type MockTaskCreateUseCaseMockRecorder struct {
	mock *MockTaskCreateUseCase
}

// NewMockTaskCreateUseCase creates a new mock instance.
func NewMockTaskCreateUseCase(ctrl *gomock.Controller) *MockTaskCreateUseCase {
	mock := &MockTaskCreateUseCase{ctrl: ctrl}
	mock.recorder = &MockTaskCreateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskCreateUseCase) EXPECT() *MockTaskCreateUseCaseMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskCreateUseCase) CreateTask(ctx context.Context, task entity.Task) (entity.IdTask, entity.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(entity.IdTask)
	ret1, _ := ret[1].(entity.Status)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskCreateUseCaseMockRecorder) CreateTask(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskCreateUseCase)(nil).CreateTask), ctx, task)
}

// MockTaskGetUseCase is a mock of TaskGetUseCase interface.
type MockTaskGetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskGetUseCaseMockRecorder
}

// MockTaskGetUseCaseMockRecorder is the mock recorder for MockTaskGetUseCase.
type MockTaskGetUseCaseMockRecorder struct {
	mock *MockTaskGetUseCase
}

// NewMockTaskGetUseCase creates a new mock instance.
func NewMockTaskGetUseCase(ctrl *gomock.Controller) *MockTaskGetUseCase {
	mock := &MockTaskGetUseCase{ctrl: ctrl}
	mock.recorder = &MockTaskGetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskGetUseCase) EXPECT() *MockTaskGetUseCaseMockRecorder {
	return m.recorder
}

// GetTask mocks base method.
func (m *MockTaskGetUseCase) GetTask(ctx context.Context, id entity.IdTask) (*entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(*entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskGetUseCaseMockRecorder) GetTask(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskGetUseCase)(nil).GetTask), ctx, id)
}

// MockTaskFileUseCase is a mock of TaskFileUseCase interface.
type MockTaskFileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskFileUseCaseMockRecorder
}

// MockTaskFileUseCaseMockRecorder is the mock recorder for MockTaskFileUseCase.
type MockTaskFileUseCaseMockRecorder struct {
	mock *MockTaskFileUseCase
}

// NewMockTaskFileUseCase creates a new mock instance.
func NewMockTaskFileUseCase(ctrl *gomock.Controller) *MockTaskFileUseCase {
	mock := &MockTaskFileUseCase{ctrl: ctrl}
	mock.recorder = &MockTaskFileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskFileUseCase) EXPECT() *MockTaskFileUseCaseMockRecorder {
	return m.recorder
}

// GetTaskFile mocks base method.
func (m *MockTaskFileUseCase) GetTaskFile(ctx context.Context, idTask entity.IdTask, idFile entity.IdFile) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskFile", ctx, idTask, idFile)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskFile indicates an expected call of GetTaskFile.
func (mr *MockTaskFileUseCaseMockRecorder) GetTaskFile(ctx, idTask, idFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskFile", reflect.TypeOf((*MockTaskFileUseCase)(nil).GetTaskFile), ctx, idTask, idFile)
}
