// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ErrorCode.
const (
	BADREQUEST          ErrorCode = "BAD_REQUEST"
	FORBIDDEN           ErrorCode = "FORBIDDEN"
	INTERNALSERVERERROR ErrorCode = "INTERNAL_SERVER_ERROR"
	NOTFOUND            ErrorCode = "NOT_FOUND"
	TIMEOUT             ErrorCode = "TIMEOUT"
)

// Defines values for TaskStatus.
const (
	DONE    TaskStatus = "DONE"
	PROCESS TaskStatus = "PROCESS"
)

// DownloadsIdResponse defines model for DownloadsIdResponse.
type DownloadsIdResponse struct {
	Files []DownloadsIdResponse_Files_Item `json:"files"`

	// Id ID заявки, по которому можно опрашивать статус скачивания файлов
	Id IdTask `json:"id"`

	// Status Статус заявки
	Status TaskStatus `json:"status"`
}

// DownloadsIdResponse_Files_Item defines model for DownloadsIdResponse.files.Item.
type DownloadsIdResponse_Files_Item struct {
	union json.RawMessage
}

// DownloadsRequest defines model for DownloadsRequest.
type DownloadsRequest struct {
	// Files массив URL для скачивания
	Files []Url `json:"files"`

	// Timeout таймаут в секундах
	Timeout string `json:"timeout"`
}

// DownloadsResponse defines model for DownloadsResponse.
type DownloadsResponse struct {
	// Id ID заявки, по которому можно опрашивать статус скачивания файлов
	Id IdTask `json:"id"`

	// Status Статус заявки
	Status TaskStatus `json:"status"`
}

// ErrorCode Код ошибки для файла
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Код ошибки для файла
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// IdTask ID заявки, по которому можно опрашивать статус скачивания файлов
type IdTask = int

// TaskStatus Статус заявки
type TaskStatus string

// Url defines model for Url.
type Url struct {
	// Url URL для скачивания файла
	Url UrlString `json:"url"`
}

// UrlErr defines model for UrlErr.
type UrlErr struct {
	Error struct {
		Code string `json:"code"`
	} `json:"error"`

	// Url URL для скачивания файла
	Url UrlString `json:"url"`
}

// UrlFile defines model for UrlFile.
type UrlFile struct {
	FileId int `json:"file_id"`

	// Url URL для скачивания файла
	Url UrlString `json:"url"`
}

// UrlString URL для скачивания файла
type UrlString = string

// IdFilePar defines model for IdFilePar.
type IdFilePar = int

// IdTaskPar defines model for IdTaskPar.
type IdTaskPar = int

// BadRequest400 defines model for BadRequest400.
type BadRequest400 = ErrorResponse

// InternalServerError500 defines model for InternalServerError500.
type InternalServerError500 = ErrorResponse

// NotFound404 defines model for NotFound404.
type NotFound404 = ErrorResponse

// PostDownloadsJSONRequestBody defines body for PostDownloads for application/json ContentType.
type PostDownloadsJSONRequestBody = DownloadsRequest

// AsUrlFile returns the union data inside the DownloadsIdResponse_Files_Item as a UrlFile
func (t DownloadsIdResponse_Files_Item) AsUrlFile() (UrlFile, error) {
	var body UrlFile
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUrlFile overwrites any union data inside the DownloadsIdResponse_Files_Item as the provided UrlFile
func (t *DownloadsIdResponse_Files_Item) FromUrlFile(v UrlFile) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUrlFile performs a merge with any union data inside the DownloadsIdResponse_Files_Item, using the provided UrlFile
func (t *DownloadsIdResponse_Files_Item) MergeUrlFile(v UrlFile) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsUrlErr returns the union data inside the DownloadsIdResponse_Files_Item as a UrlErr
func (t DownloadsIdResponse_Files_Item) AsUrlErr() (UrlErr, error) {
	var body UrlErr
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUrlErr overwrites any union data inside the DownloadsIdResponse_Files_Item as the provided UrlErr
func (t *DownloadsIdResponse_Files_Item) FromUrlErr(v UrlErr) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUrlErr performs a merge with any union data inside the DownloadsIdResponse_Files_Item, using the provided UrlErr
func (t *DownloadsIdResponse_Files_Item) MergeUrlErr(v UrlErr) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t DownloadsIdResponse_Files_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DownloadsIdResponse_Files_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Download files
	// (POST /downloads)
	PostDownloads(w http.ResponseWriter, r *http.Request)
	// Просмотр статусов
	// (GET /downloads/{id})
	GetDownloadsId(w http.ResponseWriter, r *http.Request, id IdTaskPar)
	// Скачивание файла
	// (GET /downloads/{id}/files/{file_id})
	GetDownloadsIdFilesFileId(w http.ResponseWriter, r *http.Request, id IdTaskPar, fileId IdFilePar)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Download files
// (POST /downloads)
func (_ Unimplemented) PostDownloads(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Просмотр статусов
// (GET /downloads/{id})
func (_ Unimplemented) GetDownloadsId(w http.ResponseWriter, r *http.Request, id IdTaskPar) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Скачивание файла
// (GET /downloads/{id}/files/{file_id})
func (_ Unimplemented) GetDownloadsIdFilesFileId(w http.ResponseWriter, r *http.Request, id IdTaskPar, fileId IdFilePar) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDownloads operation middleware
func (siw *ServerInterfaceWrapper) PostDownloads(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDownloads(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDownloadsId operation middleware
func (siw *ServerInterfaceWrapper) GetDownloadsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id IdTaskPar

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownloadsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDownloadsIdFilesFileId operation middleware
func (siw *ServerInterfaceWrapper) GetDownloadsIdFilesFileId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id IdTaskPar

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "file_id" -------------
	var fileId IdFilePar

	err = runtime.BindStyledParameterWithLocation("simple", false, "file_id", runtime.ParamLocationPath, chi.URLParam(r, "file_id"), &fileId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownloadsIdFilesFileId(w, r, id, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/downloads", wrapper.PostDownloads)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads/{id}", wrapper.GetDownloadsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/downloads/{id}/files/{file_id}", wrapper.GetDownloadsIdFilesFileId)
	})

	return r
}

type BadRequest400JSONResponse ErrorResponse

type InternalServerError500JSONResponse ErrorResponse

type NotFound404JSONResponse ErrorResponse

type PostDownloadsRequestObject struct {
	Body *PostDownloadsJSONRequestBody
}

type PostDownloadsResponseObject interface {
	VisitPostDownloadsResponse(w http.ResponseWriter) error
}

type PostDownloads201JSONResponse DownloadsResponse

func (response PostDownloads201JSONResponse) VisitPostDownloadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostDownloads400JSONResponse struct{ BadRequest400JSONResponse }

func (response PostDownloads400JSONResponse) VisitPostDownloadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostDownloads500JSONResponse struct {
	InternalServerError500JSONResponse
}

func (response PostDownloads500JSONResponse) VisitPostDownloadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsIdRequestObject struct {
	Id IdTaskPar `json:"id"`
}

type GetDownloadsIdResponseObject interface {
	VisitGetDownloadsIdResponse(w http.ResponseWriter) error
}

type GetDownloadsId200JSONResponse DownloadsIdResponse

func (response GetDownloadsId200JSONResponse) VisitGetDownloadsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsId400JSONResponse struct{ BadRequest400JSONResponse }

func (response GetDownloadsId400JSONResponse) VisitGetDownloadsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsId404JSONResponse struct{ NotFound404JSONResponse }

func (response GetDownloadsId404JSONResponse) VisitGetDownloadsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsId500JSONResponse struct {
	InternalServerError500JSONResponse
}

func (response GetDownloadsId500JSONResponse) VisitGetDownloadsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsIdFilesFileIdRequestObject struct {
	Id     IdTaskPar `json:"id"`
	FileId IdFilePar `json:"file_id"`
}

type GetDownloadsIdFilesFileIdResponseObject interface {
	VisitGetDownloadsIdFilesFileIdResponse(w http.ResponseWriter) error
}

type GetDownloadsIdFilesFileId200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetDownloadsIdFilesFileId200ApplicationoctetStreamResponse) VisitGetDownloadsIdFilesFileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetDownloadsIdFilesFileId400JSONResponse struct{ BadRequest400JSONResponse }

func (response GetDownloadsIdFilesFileId400JSONResponse) VisitGetDownloadsIdFilesFileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsIdFilesFileId404JSONResponse struct{ NotFound404JSONResponse }

func (response GetDownloadsIdFilesFileId404JSONResponse) VisitGetDownloadsIdFilesFileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDownloadsIdFilesFileId500JSONResponse struct {
	InternalServerError500JSONResponse
}

func (response GetDownloadsIdFilesFileId500JSONResponse) VisitGetDownloadsIdFilesFileIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Download files
	// (POST /downloads)
	PostDownloads(ctx context.Context, request PostDownloadsRequestObject) (PostDownloadsResponseObject, error)
	// Просмотр статусов
	// (GET /downloads/{id})
	GetDownloadsId(ctx context.Context, request GetDownloadsIdRequestObject) (GetDownloadsIdResponseObject, error)
	// Скачивание файла
	// (GET /downloads/{id}/files/{file_id})
	GetDownloadsIdFilesFileId(ctx context.Context, request GetDownloadsIdFilesFileIdRequestObject) (GetDownloadsIdFilesFileIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHttpHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHttpMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostDownloads operation middleware
func (sh *strictHandler) PostDownloads(w http.ResponseWriter, r *http.Request) {
	var request PostDownloadsRequestObject

	var body PostDownloadsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDownloads(ctx, request.(PostDownloadsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDownloads")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDownloadsResponseObject); ok {
		if err := validResponse.VisitPostDownloadsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDownloadsId operation middleware
func (sh *strictHandler) GetDownloadsId(w http.ResponseWriter, r *http.Request, id IdTaskPar) {
	var request GetDownloadsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDownloadsId(ctx, request.(GetDownloadsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDownloadsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDownloadsIdResponseObject); ok {
		if err := validResponse.VisitGetDownloadsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDownloadsIdFilesFileId operation middleware
func (sh *strictHandler) GetDownloadsIdFilesFileId(w http.ResponseWriter, r *http.Request, id IdTaskPar, fileId IdFilePar) {
	var request GetDownloadsIdFilesFileIdRequestObject

	request.Id = id
	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDownloadsIdFilesFileId(ctx, request.(GetDownloadsIdFilesFileIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDownloadsIdFilesFileId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDownloadsIdFilesFileIdResponseObject); ok {
		if err := validResponse.VisitGetDownloadsIdFilesFileIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY3W7bxhJ+FWJO7g4TKeckQKq7OJILAYnlSnZvAtfYkmubqchldldpDUOAJadogQQw",
	"UPSqQFEUfQFFsFrFtpRXmH2jYpaURFuU5fw0uemNIZGjmdlvvpn51gfgiTAWEY+0gtIBxEyykGsu7beq",
	"vxo0+TqT9MXnypNBrAMRQQnwDxzhEE+xh2fmJY7MC3zt4BBPcIAj08WheZ68Nl0cm0MH/8KeOcY+nuLQ",
	"wRH2HNOxr3/AIfaxZ70NwIWAvMdM74ELEQs5lGAnaPLtwAcXJH/aCiT3oaRli7ugvD0eMspO78dkGkSa",
	"73IJ7bYLVX+DqW8+efZvm3ibrFUsIsVtEVaYX+dPW1zpO8UiPfBEpHmk6SOL42bgMTpV4Ymiox1kXN+Q",
	"fAdK8J/CrMaF5K0qVKQUsp7GSaJeguhXHOApnd4c0ifTxRGOceCYLg7wDMcWFHxjDnFsOtgDQjzSXEas",
	"2eDyGZc2xN2PmvNPODJHpmszHuHIHJtjB8fmRxziK6oXlW1gDrGPw0nOa0Kvilbk3yne+YiJ/mw5Q7wb",
	"EJ/snx6+Tgn4wvI39UbByuLbqCmYr6r+1C11qxQxlzpIiEJtYj8Emof2g4h4bQdKj6/OdlM2qc2h7S61",
	"q0gJ7S13Qlrx9RPuaUIxfcCkZPv0PfCXYZR0J9kqzXRLLbMn60ZimbTIpKEeJx2WenFTGPKSnKKY9tMV",
	"EF4q1zn2TMd0qNmdzfpDB0/wzBznDAFzTENggv8SNPOA00HIRUvP52C6liCUyZHpOti3XMZTc4QjPMGe",
	"+R5cmjzUgVCCrx4Xb3629V91A6YxlJZBtDuHXnLmWeQlyC1i3yereF6+tgEfCJ/n1PIXHONJdioMp+V8",
	"biE+wx64wKNWSKE2qo8qtc0NcGGttrG9WttcK4MLq7X6SrVcrqyBCyv3y9v1yheblQZZVdc2KvW1+w+3",
	"G5X6l5X6dqVer9UzSU6qkCa5GFAvTX/poLHnbLsQcqXYLs8slQUVt55n9nkAprWaQ69avrALXQff0Cag",
	"PWE3JY7x3Bw5eI5j/JMWhoNjuyN6Fu4+bVTz0jEdorPpmiPTye2iWS3G2J9ReLolXciwY77Gv2fcZ/PN",
	"1HW9XntQaTTAhXJtrZJbIGrRubK0kodLWruRjzz9OA/udLTOBeNU38XUuEaZ86K99xHcNLGtJHW7PXJn",
	"6XYyFear9wFSmPhPk0ht57iwZFxfbPodIUOmoQQtGeQMTlps0Y6YD9IIwrjJnfvrVUcLx5Ocae46u1w7",
	"LPIdQoVp7ojICUXENZP7DgtFizQ3zV1N8MEjEfF9h6RT4FlX4MIzLlUS4fat4q0iISdiHrE4gBL83z6y",
	"Q3/PIl7wJ2PaVkMondca87qV8BnbTXKe6t8x9tPOfmP10oA2DAmWSX+TWnllxeERNXPHvLCtenoLbIbS",
	"qqaqDyVYF0pP10eqhLnSK8Lfv4be4t8xQnYRV9LXqlCNAk0Toc6fQtu9pkyb0wPti0wjqX5Zjf+vePsf",
	"SVvF75T3YolZFl4r5JFO2eiT+/QCked7esjCxftG24W71/nVAulvdWwrDJnctzkliTuJ5qCXM84WDgK/",
	"TYF2eR5vf0svGue0aq59JcswlSwyS2WeqZ9zndHZtrFml+EFGnpmUphdN0khXyLNh7sE5V0FcsqvWp7H",
	"lXr3qqf3oat/lb08fVCmzJU7qxisJsghT8HSqnCQboYryJQ3BGeLIBl91bJjQ1pWOTi0D7LL4ir20EpU",
	"9Of9iORew3jyL5q3ZJ3wNNc3lZachf+y7xL7ruZHcmJlPSQVtXIG9rSOS4VCU3isuSeULt0r3itCe6v9",
	"dwAAAP//QByhXGYTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
